mode: "denoise"
batch_size: 14
learning_rate: 0.01
adam_b1: 0.5
adam_b2: 0.999
max_epochs: 50
cosine_scheduler_max_epoch: 50
num_workers: 8
encoder_name: "resnet34"

noise_exponential_sampling_lambda: 8

data_path_a: "/home/thomas/datasets/denoising_diffusion_deep_fake/tom_3_w448_h448/images.txt"
data_path_b: "/home/thomas/datasets/denoising_diffusion_deep_fake/georgia_3_w448_h448/images.txt"

mean_a: [0.5,0.5,0.5]
std_a: [0.5,0.5,0.5]
mean_b: [0.5,0.5,0.5]
std_b: [0.5,0.5,0.5]

