batch_size: 16
learning_rate: 0.01
adam_b1: 0.5
adam_b2: 0.999
max_epochs: 200
cosine_scheduler_max_epoch: 200
num_workers: 8
encoder_name: "resnet18"

noise_scheduler_max_epoch: 10

denoising_model_a: "/home/thomas/co/denoising_diffusion_deep_fake/d3f/lightning_logs/version_76/checkpoints/epoch=99-step=56699.ckpt"
denoising_model_b: "/home/thomas/co/denoising_diffusion_deep_fake/d3f/lightning_logs/version_77/checkpoints/epoch=99-step=56499.ckpt"

data_path_a: "/home/thomas/datasets/denoising_diffusion_deep_fake/tom_3_w448_h448/images.txt"
data_path_b: "/home/thomas/datasets/denoising_diffusion_deep_fake/georgia_3_w448_h448/images.txt"

mean_a: [128,128,128]
std_a: [128,128,128]
mean_b: [128,128,128]
std_b: [128,128,128]

