batch_size: 14
learning_rate: 0.0001
adam_b1: 0.5
adam_b2: 0.999
max_epochs: 1000
cosine_scheduler_max_epoch: 99999
num_workers: 8
encoder_name: "resnet34"

noise_exponential_sampling_lambda: 8

denoising_model_a: "/home/thomas/co/denoising_diffusion_deep_fake/d3f/lightning_logs/version_0/checkpoints/epoch=99-step=56699.ckpt"
denoising_model_b: "/home/thomas/co/denoising_diffusion_deep_fake/d3f/lightning_logs/version_1/checkpoints/epoch=99-step=56499.ckpt"

data_path_a: "/home/thomas/datasets/denoising_diffusion_deep_fake/tom_3_w448_h448/images.txt"
data_path_b: "/home/thomas/datasets/denoising_diffusion_deep_fake/georgia_3_w448_h448/images.txt"

mean_a: [0.5,0.5,0.5]
std_a: [0.5,0.5,0.5]
mean_b: [0.5,0.5,0.5]
std_b: [0.5,0.5,0.5]

