batch_size: 16
learning_rate: 0.02
max_epochs: 100
cosine_scheduler_max_epoch: 100
num_workers: 8
encoder_name: "resnet34"

noise_exponential_sampling_lambda: 5

mean: [128,128,128]
std: [128,128,128]


