batch_size: 64
learning_rate: 0.001
adam_b1: 0.5
adam_b2: 0.999
max_epochs: 1000
cosine_scheduler_max_epoch: 1000
num_workers: 8
encoder_name: "resnet34"

log_images_every_n_steps: 100

random_blur_kernel_size_list: [0,3,5,7,9,11,15,17]
random_blur_choice_weight_list: [3,1,1,1,1,1,1,1]

data_path_a: "/home/thomas/datasets/denoising_diffusion_deep_fake/tom_w128_h128"
mean_a: [128,128,128]
std_a: [128,128,128]

data_path_b: "/home/thomas/datasets/denoising_diffusion_deep_fake/georgia_w128_h128"
mean_b: [128,128,128]
std_b: [128,128,128]

image_width: 128
image_height: 128